language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1
  include:
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - COVERALLS=1

before_script:
  - ./travis/before_script.sh

script:
  - ./travis/script.sh

after_script:
  - ./travis/after_success.sh

notifications:
  email: false
