language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1
  include:
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - COVERALLS=1

before_script:
  - chmod -R +x ./travis/
  - ./travis/before_script.sh
  - echo "<?php
     class DATABASE_CONFIG {
       public \$default = array(
            'datasource' => 'Database/Mysql',
            'database' => 'cakephp_test',
            'host' => '127.0.0.1',
            'login' => 'travis',
            'persistent' => false,
       );
     }" > app/Config/database.php

script:
  - ./travis/script.sh

after_script:
  - ./travis/after_success.sh

notifications:
  email: false
