language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1
  include:
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - COVERALLS=1

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - chmod -R +x ./travis/
  - ./travis/before_script.sh
  - sh -c "if [ '$DB' = 'mysql' ]; then cat ./app/Config/database.php; fi"

script:
  - ./travis/script.sh

after_script:
  - ./travis/after_success.sh

notifications:
  email: false
